name: defect_report_mobile
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  http: ^1.3.0
  fl_chart: ^0.70.2
  flutter_typeahead: ^5.2.0
  dropdown_search: ^6.0.2
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0

flutter:
  assets:
  - assets/logo.png

  uses-material-design: true
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  # example:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
